### ISSUE TITLE
Doesn't work with Angular Universal (SSR)

### ISSUE THREAD

**Issue by elementalPRESS** [maxandriani/ngx-google-analytics#25]
Hi,

do you plan an update so that it can be used with Angular universal (SSR)? That would be really great!!

Thx!

**Comment by Zaklinatel** [comment]
I think GA metrics is not intended to work with SSR or on any servers at all, it just not make a sense. This metrics collects info about user's behavior on the web-page in real time. If you need to use GA in your angular app with SSR, you need to separate server and browser modules and import NgxGoogleAnalyticsModule in browser version only, so you can use GA metrics as intended.

Here is example from my project with SSR where I use Yandex metric. I split main module by two different: for server and for browser, so NgxGoogleAnalyticsModule just will not going to load on sever but will work at client side.

### app.browser.module.ts:
```typescript
@NgModule({
  imports: [
    // Common module for server and browser both
    AppModule,

    // Browser-only imports
    NgxMetrikaModule.forRoot( /* ... */ ),
    NgxGoogleAnalyticsModule.forRoot( /* .. */ )
  ],
  bootstrap: [AppComponent],
})
export class AppBrowserModule {
  /* ... */
}
```

### app.server.module.ts:
```typescript
@NgModule({
  imports: [
    AppModule,
    ServerModule,
  ],
  bootstrap: [AppComponent],
})
export class AppServerModule { }
```

### in main.ts
```typescript
document.addEventListener('DOMContentLoaded', () => {
  platformBrowserDynamic().bootstrapModule(AppBrowserModule) // note now bootstrapped App*Browser*Module
  .catch(err => console.error(err));
});
```
### in main.server.ts
```typescript
export { AppServerModule } from './app/app.server.module';
```

**Comment by maxandriani** [comment]
Hi @elementalPRESS!

As @Zaklinatel has pointed there are some arquitectural differences between browser and SSR applications. I know angular provides a guide to work arround browser api calls on SSR (https://angular.io/guide/universal#working-around-the-browser-apis), but it only solves half of the problems. I can update this lib to use all APIs abstractions, but it will only not break the build or application executions. But it will not make GA works on server side.

The other half of the problem is GA lib itself, that make direct access to browsers api like window and document. So, once I import the GA script tag it will never works on server side. Also the @Zaklinatel solution is actually a very good choise.

I do not have time to work on this feature write now because I'm finishing my MBA. But I'll accept any PR that do not break unit tests.

**Comment by martinobaid** [comment]
Agreed, @Zaklinatel great splitting of modules. I haven't got around to splitting modules between app and server rather only have a module to share between but that's true packages like this don't need to be exposed at all server-side. Also what I've done atm if it'll help anyone is having a single function in AppComponent calling router event rather than manually on every page (without using the analytics-router module since I'm also running an SSR app and don't want unnecessary clashes), on app component init I call the analytics function:

` private triggerAnalyticsPageView(): void {
        if (isPlatformBrowser(this.platformId)) {
            this.router.events
                .pipe(filter(e => e instanceof NavigationEnd))
                .subscribe((event: NavigationEnd) => {
                    this.googleAnalytics.pageView(event.urlAfterRedirects, undefined);
                });
        }
    }`

Less boilerplate code, put in a single place rather than on every other page manually.

**Comment by maxandriani** [comment]
@martinobaid Interesting idea do check platform before subscribe router events. The GARouterModule is just a sugar to add a hook on `APP_BOOTSTRAP_LISTENER`. Can you please try to use the following code on your project w/ the platform check? If works I'll add this check on GARouterModule.

https://github.com/maxandriani/ngx-google-analytics/blob/master/projects/ngx-google-analytics/src/lib/initializers/google-analytics-router.initializer.ts

**Comment by martinobaid** [comment]
Did wrap the function with isPlatformCheck but it's still throwing 'Was not possible create or read gtag() fn. Make sure this module is running on a Browser w/ access to Window interface.' in the console. Not sure how you wanted it done exactly, doesn't look like that file has any call signatures so I just copy-pasted that code into the triggerAnalyticsPageView function I had. [https://imgur.com/8mYYLKU](url)

**Comment by maxandriani** [comment]
Yep, sorry @martinobaid. It will not work at all. I reviewed all source code and I need to call window.gtag() on the very beginning of Angular initilaization. I'll be a big architecture refactor to provide some kind of lazy initialization. I don't think it worth it.

@Zaklinatel provides a good workarround! I hope his solution fit you guys use case scenarios.
